#ifndef _EEPROM_H_
#define _EEPROM_H_

// Structures and defines
typedef enum {
    EEPADDR_I2C_ADDRESS_8bits = 0,
    EEPADDR_ENABLED_TELEMETER_BITFIELD,   // Telemeters 1...12 - LSB align
    EEPADDR_THRESHOLD_ALERT_TELEMETER_1,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_2,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_3,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_4,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_5,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_6,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_7,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_8,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_9,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_10,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_11,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_12,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_13,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_14,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_15,
    EEPADDR_THRESHOLD_ALERT_TELEMETER_16,
    // _________
    EEPADDR_MAGIC_NUMBER,
    // _________
    EEPROM_SIZE,
    EEPADDR_CHECKSUM
}tEEPADDR_addresses;

#define EEPROM_MAGIC_NUMBER         (0x5A96)
#define EEPROM_WRITE_ENABLED_CODE   (0x5A)
#define EEPROM_RESET_FACTORY_CODE   (0x69)

// Functions prototypes
void Init_EEPROM(); 
void readEEPROM();
void saveEEPROM();
void forceEEPROMDefaultValues();
void resetFactoryEEPROM();

// External data
extern unsigned short EEPROM_values[];




#endif // _EEPROM_H_
